### ISSUE TITLE
Could not generate MIDI file, pls help me, Thanks!

### ISSUE THREAD

**Issue by mikmeng** [GalacticGlum/composer#10]
I have already trained the model, but when I generate midi file, there are lots of errors. Pls help me have a look, thank you!

(composer) root@fake-server:/opt/composer# composer generate music_rnn  ./output/logdir/music_rnn-2020-06-16_10-37-25/. ./output/logdir/music_rnn-2020-06-16_10-37-25/.
2020-06-16 14:32:03.973826: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-16 14:32:04.544392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:21:01.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-06-16 14:32:04.544624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-16 14:32:04.546146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-16 14:32:04.547648: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-16 14:32:04.547933: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-16 14:32:04.549479: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-16 14:32:04.550405: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-16 14:32:04.553678: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-16 14:32:04.555097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-16 14:32:04.555379: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-06-16 14:32:04.562067: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2600000000 Hz
2020-06-16 14:32:04.562446: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ac05acfcb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-16 14:32:04.562470: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-16 14:32:04.651104: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ac05ad17d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-16 14:32:04.651136: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-06-16 14:32:04.651997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:21:01.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-06-16 14:32:04.652041: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-16 14:32:04.652055: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-16 14:32:04.652071: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-16 14:32:04.652084: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-16 14:32:04.652103: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-16 14:32:04.652118: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-16 14:32:04.652131: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-16 14:32:04.653507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-16 14:32:04.653561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-16 14:32:04.654625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-16 14:32:04.654644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-16 14:32:04.654651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-16 14:32:04.656145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14099 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:21:01.0, compute capability: 7.5)
MusicRNN model restored from './output/logdir/music_rnn-2020-06-16_10-37-25/./ckpt-130' (global_step=65000, epoch=9).
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/composer/bin/composer", line 11, in <module>
    load_entry_point('composer', 'console_scripts', 'composer')()
  File "/usr/local/anaconda3/envs/composer/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/composer/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/composer/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/envs/composer/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/composer/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/composer/composer/cli.py", line 643, in generate
    raise NotImplementedError()
NotImplementedError
(composer) root@fake-server:/opt/composer#

**Comment by mikmeng** [comment]
Sorry, I solve it.

**Comment by GalacticGlum** [comment]
Just for reference, for anyone else who experiences a similar issue, at this time, the ``generate`` CLI command requires a prompt as an input. If you don't want to prompt the model with any MIDI file, you can just prompt with an empty token (such as BOS) or something like TIME_SHIFT or SET_VELOCITY.
